name: TP Escalabilidad - Coffee Shop Analysis
services:
  middleware:
    container_name: middleware
    build:
      context: ./middleware
      dockerfile: Dockerfile
    ports:
      - '15672:15672'
    networks:
      - testing_net
    volumes:
      - ./middleware/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro

  results:
    container_name: results
    image: results:latest
    entrypoint: python3 /results/main.py
    environment:
      - PYTHONUNBUFFERED=1
      - DIR_PATH=/storage
    networks:
      - testing_net
    depends_on:
      - middleware
    volumes:
      - ./results/config.ini:/config.ini:ro
      - ./.data/storage:/results/storage

  server:
    container_name: server
    image: server:latest
    entrypoint: python3 /server/main.py
    environment:
      - PYTHONUNBUFFERED=1
      - DISPATCHERS=dispatcher1:12347,dispatcher2:12348
    networks:
      - testing_net
    depends_on:
      - dispatcher1
      - dispatcher2
    volumes:
      - ./server/config.ini:/config.ini:ro

  client1:
    container_name: client1
    image: client:latest
    entrypoint: python3 /client/main.py
    environment:
      - PYTHONUNBUFFERED=1
      - INPUT_DIR=/input
      - OUTPUT_DIR=/output
      - EXECUTIONS=1
    networks:
      - testing_net
    depends_on:
      - server
    volumes:
      - ./client/config.ini:/config.ini:ro
      - ./.data/archive:/input:ro
      - ./.data/results/client1:/output:rw

  client2:
    container_name: client2
    image: client:latest
    entrypoint: python3 /client/main.py
    environment:
      - PYTHONUNBUFFERED=1
      - INPUT_DIR=/input
      - OUTPUT_DIR=/output
      - EXECUTIONS=1
    networks:
      - testing_net
    depends_on:
      - server
    volumes:
      - ./client/config.ini:/config.ini:ro
      - ./.data/archive:/input:ro
      - ./.data/results/client2:/output:rw
      
  dispatcher1:
    container_name: dispatcher1
    image: dispatcher:latest
    entrypoint: python3 /dispatcher/main.py
    environment:
      - PYTHONUNBUFFERED=1
      - PORT=12347
    networks:
      - testing_net
    depends_on:
      - middleware
    volumes:
      - ./dispatcher/config.ini:/config.ini:ro

  dispatcher2:
    container_name: dispatcher2
    image: dispatcher:latest
    entrypoint: python3 /dispatcher/main.py
    environment:
      - PYTHONUNBUFFERED=1
      - PORT=12348
    networks:
      - testing_net
    depends_on:
      - middleware
    volumes:
      - ./dispatcher/config.ini:/config.ini:ro

  resultnode1:
    container_name: resultnode1
    image: resultnode:latest
    entrypoint: python3 /resultnode/main.py
    environment:
      - RESULT_NODE_ID=1
    networks:
      - testing_net
    depends_on:
      - middleware
      - results
    volumes:
      - ./resultnode/config.ini:/config.ini:ro


  selectnode1:
    container_name: selectnode1
    image: selectnode:latest
    entrypoint: python3 /selectnode/main.py
    environment:
      - SELECT_NODE_ID=1
      - GROUPBY_NODE_COUNT=2
      - JOIN_NODE_COUNT=2
    networks:
      - testing_net
    depends_on:
      - middleware
    links:
      - middleware
    volumes:
      - ./selectnode/config.ini:/config.ini:ro

  selectnode2:
    container_name: selectnode2
    image: selectnode:latest
    entrypoint: python3 /selectnode/main.py
    environment:
      - SELECT_NODE_ID=2
      - GROUPBY_NODE_COUNT=2
      - JOIN_NODE_COUNT=2
    networks:
      - testing_net
    depends_on:
      - middleware
    links:
      - middleware
    volumes:
      - ./selectnode/config.ini:/config.ini:ro

  selectnode3:
    container_name: selectnode3
    image: selectnode:latest
    entrypoint: python3 /selectnode/main.py
    environment:
      - SELECT_NODE_ID=3
      - GROUPBY_NODE_COUNT=2
      - JOIN_NODE_COUNT=2
    networks:
      - testing_net
    depends_on:
      - middleware
    links:
      - middleware
    volumes:
      - ./selectnode/config.ini:/config.ini:ro

  groupbynode1:
    container_name: groupbynode1
    image: groupbynode:latest
    entrypoint: python3 /groupbynode/main.py
    environment:
      - NODE_IND=0
      - NODE_COUNT=2
      - JOIN_NODE_COUNT=2
    networks:
      - testing_net
    depends_on:
      - middleware
    links:
      - middleware
    volumes:
      - ./groupbynode/config.ini:/config.ini:ro

  groupbynode2:
    container_name: groupbynode2
    image: groupbynode:latest
    entrypoint: python3 /groupbynode/main.py
    environment:
      - NODE_IND=1
      - NODE_COUNT=2
      - JOIN_NODE_COUNT=2
    networks:
      - testing_net
    depends_on:
      - middleware
    links:
      - middleware
    volumes:
      - ./groupbynode/config.ini:/config.ini:ro

  joinnode1:
    container_name: joinnode1
    image: joinnode:latest
    entrypoint: python3 /joinnode/main.py
    environment:
      - NODE_IND=0
      - NODE_COUNT=2
      - NODE_ID=0
    networks:
      - testing_net
    depends_on:
      - middleware
    links:
      - middleware
    volumes:
      - ./joinnode/config.ini:/config.ini:ro
  
  joinnode2:
    container_name: joinnode2
    image: joinnode:latest
    entrypoint: python3 /joinnode/main.py
    environment:
      - NODE_IND=1
      - NODE_COUNT=2
      - NODE_ID=0
    networks:
      - testing_net
    depends_on:
      - middleware
    links:
      - middleware
    volumes:
      - ./joinnode/config.ini:/config.ini:ro
      

networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24
