name: TP Escalabilidad - Coffee Shop Analysis
services:
  supervisor1:
    container_name: supervisor1
    image: supervisor:latest
    entrypoint: python3 /supervisor/main.py
    environment:
      - SUPERVISOR_ID=1
      - SUPERVISOR_PEERS=1:supervisor1:6000,2:supervisor2:6000
    networks:
      - testing_net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./supervisor/config.ini:/config.ini:ro

  supervisor2:
    container_name: supervisor2
    image: supervisor:latest
    entrypoint: python3 /supervisor/main.py
    environment:
      - SUPERVISOR_ID=2
      - SUPERVISOR_PEERS=1:supervisor1:6000,2:supervisor2:6000
    networks:
      - testing_net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./supervisor/config.ini:/config.ini:ro

  middleware:
    container_name: middleware
    build:
      context: ./middleware
      dockerfile: Dockerfile
    ports:
      - '15672:15672'
    networks:
      - testing_net
    volumes:
      - ./middleware/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro

  results1:
    container_name: results1
    image: results:latest
    entrypoint: python3 /results/main.py
    environment:
      - PYTHONUNBUFFERED=1
      - DIR_PATH=/storage
      - PORT=12349
      - NODE_ID=1
    networks:
      - testing_net
    depends_on:
      - middleware
    volumes:
      - ./results/config.ini:/config.ini:ro
      - ./.data/storage/results_1:/results/storage
      - ./config_health.ini:/config_health.ini:ro
      - ./.data/states/:/etc/node_state

  results2:
    container_name: results2
    image: results:latest
    entrypoint: python3 /results/main.py
    environment:
      - PYTHONUNBUFFERED=1
      - DIR_PATH=/storage
      - PORT=12350
      - NODE_ID=2
    networks:
      - testing_net
    depends_on:
      - middleware
    volumes:
      - ./results/config.ini:/config.ini:ro
      - ./.data/storage/results_2:/results/storage
      - ./config_health.ini:/config_health.ini:ro
      - ./.data/states/:/etc/node_state

  server:
    container_name: server
    image: server:latest
    entrypoint: python3 /server/main.py
    environment:
      - PYTHONUNBUFFERED=1
      - DISPATCHERS=dispatcher1:12347,dispatcher2:12348
      - RESULTS_STORAGES=results1:12349,results2:12350
    networks:
      - testing_net
    depends_on:
      - dispatcher1
      - dispatcher2
    volumes:
      - ./server/config.ini:/config.ini:ro

  dispatcher1:
    container_name: dispatcher1
    image: dispatcher:latest
    entrypoint: python3 /dispatcher/main.py
    environment:
      - PYTHONUNBUFFERED=1
      - PORT=12347
      - NODE_ID=1
    networks:
      - testing_net
    depends_on:
      - middleware
    volumes:
      - ./dispatcher/config.ini:/config.ini:ro
      - ./.data/states/:/etc/node_state
      - ./config_health.ini:/config_health.ini:ro

  dispatcher2:
    container_name: dispatcher2
    image: dispatcher:latest
    entrypoint: python3 /dispatcher/main.py
    environment:
      - PYTHONUNBUFFERED=1
      - PORT=12348
      - NODE_ID=2
    networks:
      - testing_net
    depends_on:
      - middleware
    volumes:
      - ./dispatcher/config.ini:/config.ini:ro
      - ./.data/states/:/etc/node_state
      - ./config_health.ini:/config_health.ini:ro

  resultnode1:
    container_name: resultnode1
    image: resultnode:latest
    entrypoint: python3 /resultnode/main.py
    environment:
      - RESULT_NODE_ID=1
      - RESULTS_STORAGES_COUNT=2
    networks:
      - testing_net
    depends_on:
      - middleware
      - results1
      - results2
    volumes:
      - ./resultnode/config.ini:/config.ini:ro
      - ./.data/states/:/etc/node_state
      - ./config_health.ini:/config_health.ini:ro


  selectnode1:
    container_name: selectnode1
    image: selectnode:latest
    entrypoint: python3 /selectnode/main.py
    environment:
      - SELECT_NODE_ID=1
      - GROUPBY_NODE_COUNT=2
      - JOIN_NODE_COUNT=2
    networks:
      - testing_net
    depends_on:
      - middleware
    links:
      - middleware
    volumes:
      - ./selectnode/config.ini:/config.ini:ro
      - ./config_health.ini:/config_health.ini:ro

  selectnode2:
    container_name: selectnode2
    image: selectnode:latest
    entrypoint: python3 /selectnode/main.py
    environment:
      - SELECT_NODE_ID=2
      - GROUPBY_NODE_COUNT=2
      - JOIN_NODE_COUNT=2
    networks:
      - testing_net
    depends_on:
      - middleware
    links:
      - middleware
    volumes:
      - ./selectnode/config.ini:/config.ini:ro
      - ./config_health.ini:/config_health.ini:ro

  selectnode3:
    container_name: selectnode3
    image: selectnode:latest
    entrypoint: python3 /selectnode/main.py
    environment:
      - SELECT_NODE_ID=3
      - GROUPBY_NODE_COUNT=2
      - JOIN_NODE_COUNT=2
    networks:
      - testing_net
    depends_on:
      - middleware
    links:
      - middleware
    volumes:
      - ./selectnode/config.ini:/config.ini:ro
      - ./config_health.ini:/config_health.ini:ro


  groupbynode1_query_2:
    container_name: groupbynode1_query_2
    image: groupbynode:latest
    entrypoint: python3 /groupbynode/main.py
    environment:
      - NODE_IND=0
      - NODE_COUNT=2
      - JOIN_NODE_COUNT=2
      - Q_TYPE=query_2
    networks:
      - testing_net
    depends_on:
      - middleware
    links:
      - middleware
    volumes:
      - ./groupbynode/config.ini:/config.ini:ro
      - ./.data/states/:/etc/node_state
      - ./config_health.ini:/config_health.ini:ro
  groupbynode1_query_3:
    container_name: groupbynode1_query_3
    image: groupbynode:latest
    entrypoint: python3 /groupbynode/main.py
    environment:
      - NODE_IND=0
      - NODE_COUNT=2
      - JOIN_NODE_COUNT=2
      - Q_TYPE=query_3
    networks:
      - testing_net
    depends_on:
      - middleware
    links:
      - middleware
    volumes:
      - ./groupbynode/config.ini:/config.ini:ro
      - ./.data/states/:/etc/node_state
      - ./config_health.ini:/config_health.ini:ro
  groupbynode1_query_4:
    container_name: groupbynode1_query_4
    image: groupbynode:latest
    entrypoint: python3 /groupbynode/main.py
    environment:
      - NODE_IND=0
      - NODE_COUNT=2
      - JOIN_NODE_COUNT=2
      - Q_TYPE=query_4
    networks:
      - testing_net
    depends_on:
      - middleware
    links:
      - middleware
    volumes:
      - ./groupbynode/config.ini:/config.ini:ro
      - ./.data/states/:/etc/node_state
      - ./config_health.ini:/config_health.ini:ro



  groupbynode2_query_2:
    container_name: groupbynode2_query_2
    image: groupbynode:latest
    entrypoint: python3 /groupbynode/main.py
    environment:
      - NODE_IND=1
      - NODE_COUNT=2
      - JOIN_NODE_COUNT=2
      - Q_TYPE=query_2
    networks:
      - testing_net
    depends_on:
      - middleware
    links:
      - middleware
    volumes:
      - ./groupbynode/config.ini:/config.ini:ro
      - ./.data/states/:/etc/node_state
      - ./config_health.ini:/config_health.ini:ro
  groupbynode2_query_3:
    container_name: groupbynode2_query_3
    image: groupbynode:latest
    entrypoint: python3 /groupbynode/main.py
    environment:
      - NODE_IND=1
      - NODE_COUNT=2
      - JOIN_NODE_COUNT=2
      - Q_TYPE=query_3
    networks:
      - testing_net
    depends_on:
      - middleware
    links:
      - middleware
    volumes:
      - ./groupbynode/config.ini:/config.ini:ro
      - ./.data/states/:/etc/node_state
      - ./config_health.ini:/config_health.ini:ro
  groupbynode2_query_4:
    container_name: groupbynode2_query_4
    image: groupbynode:latest
    entrypoint: python3 /groupbynode/main.py
    environment:
      - NODE_IND=1
      - NODE_COUNT=2
      - JOIN_NODE_COUNT=2
      - Q_TYPE=query_4
    networks:
      - testing_net
    depends_on:
      - middleware
    links:
      - middleware
    volumes:
      - ./groupbynode/config.ini:/config.ini:ro
      - ./.data/states/:/etc/node_state
      - ./config_health.ini:/config_health.ini:ro

  joinnode1:
    container_name: joinnode1
    image: joinnode:latest
    entrypoint: python3 /joinnode/main.py
    environment:
      - NODE_IND=0
      - NODE_COUNT=2
      - NODE_ID=1
    networks:
      - testing_net
    depends_on:
      - middleware
    links:
      - middleware
    volumes:
      - ./joinnode/config.ini:/config.ini:ro
      - ./.data/states/:/etc/node_state
      - ./config_health.ini:/config_health.ini:ro

  joinnode2:
    container_name: joinnode2
    image: joinnode:latest
    entrypoint: python3 /joinnode/main.py
    environment:
      - NODE_IND=1
      - NODE_COUNT=2
      - NODE_ID=2
    networks:
      - testing_net
    depends_on:
      - middleware
    links:
      - middleware
    volumes:
      - ./joinnode/config.ini:/config.ini:ro
      - ./.data/states/:/etc/node_state
      - ./config_health.ini:/config_health.ini:ro
      

networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24
