services:
  integration_tests:
    container_name: integration_tests
    image: integration_tests:latest
    entrypoint: python3 /integration_tests/main.py
    networks:
      - testing_net

networks:
  testing_net:
    driver: bridge
