FIELD_QUERY_ID ="queries_id" 
FIELD_QUERY_TYPE ="queries_type" 
FIELD_PARTITION_IND ="partition_ind"
DEFAULT_PARTITION_VALUE =0
DEFAULT_QUERY_TYPE =""

EOF_SIGNAL = -1
DEFAULT_ERROR_SIGNAL= -2
#FIELD_QUERY_FIELDS ="queries_" 
